version: "3.9"

services:
  url-shortener:
    build:
      dockerfile: Dockerfile
    container_name: urShorty
    hostname: urShorty
    environment:
      - CONFIG=docker
    ports:
      -   "4000:4000"
    restart: always

  redis:
    image: redis:7.2-alpine3.18
    container_name: redis_urShorty
    hostname: redis_urShorty
    ports:
      - "6379:6379"
    restart: always