version: "3.9"

services:
  url-shortener:
    build:
      dockerfile: docker/Dockerfile
    container_name: urShorty
    hostname: urShorty
    environment:
      - CONFIG=docker
    ports:
      -   "4000:4000"
    restart: always

  redis:
    image: redis:7.2-alpine3.18
    container_name: redis_urShorty
    hostname: redis_urShorty
    ports:
      - "6379:6379"
    restart: always

  clickhouse:
    image: clickhouse/clickhouse-server:23.10.1.1976-alpine
    container_name: clickhouse_urShorty
    hostname: clickhouse_urShorty
    volumes:
      - ./data_clickhouse:/var/lib/postgresql/data
      - ./docker/clickhouse:/docker-entrypoint-initdb.d/:ro
    ports:
      - "9000:9000"
    restart: always