version: "3.9"

services:
  url-shortener:
    build:
      dockerfile: Dockerfile
    container_name: urlShorty
    hostname: urlShorty
    ports:
      -   "4000:4000"
    restart: always

  redis:
    image: redis:7.2-alpine3.18
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: always