server:
  Port: ":4000"
  SSL: false
  CtxDefaultTimeout: 12

redis:
  RedisAddr: "localhost:6379"
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

clickhouse:
  ClickhouseAddr: localhost:9000
  ClickhouseDb: "default"
  Username: "default"
  Password: ""
  MaxExecutionTime: 60
  MaxOpenConns: 5
  MaxIdleConns: 5
