name: Main

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4.1.1

      - name: go setup
        uses: action/setup-go@v5
        with:
          go-version: 1.21.4

      - name: verify dependencies
        run: go mod verify

      - name: run go vet check up
        run: go vet ./...

      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run staticcheck
        run: staticcheck ./...

      - name: install go linter
        run: go install golang.org/x/lint/golint@latest

      - name: run linter
        run: golint ./...

      - name: run tests
        run: go test -race -vet=off ./...
